baseURL = "https://nhanik.github.io"
languageCode = "en-us"
title = "Nayeem Hasan"
theme = "ezhil"

copyright = "Copyright © Nayeem Hasan"

# syntax highlighting
pygmentsstyle = "github-dark"

googleAnalytics = "G-ZFCZ8X635S"

[params]
    subtitle = "Exploring the world of softwares"

    mode = "dark"

    favicon = "icons/favicon.ico"

    customDarkCSS = "css/gray.css"

    customCSS = "css/button.css"

# menu items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

# social

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nhAnik"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nayeem-hasan-a1abb5153/"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[taxonomies]
   tag = "tags"

